# Generated by Django 2.0.7 on 2018-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('areaName', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=128)),
                ('connectorType', models.SmallIntegerField()),
                ('currentType', models.SmallIntegerField()),
                ('freeNum', models.SmallIntegerField()),
                ('chargerId', models.CharField(default='', max_length=64, unique=True)),
                ('images', models.CharField(max_length=128, null=True)),
                ('isGs', models.SmallIntegerField()),
                ('lat', models.FloatField()),
                ('link', models.SmallIntegerField()),
                ('lng', models.FloatField()),
                ('mapIcon', models.CharField(max_length=128)),
                ('maxOutPower', models.SmallIntegerField()),
                ('operatorTypes', models.CharField(max_length=32)),
                ('payType', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('plugType', models.SmallIntegerField()),
                ('priceRational', models.IntegerField()),
                ('province', models.CharField(max_length=32)),
                ('quantity', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('serviceCode', models.SmallIntegerField()),
                ('standard', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('supportOrder', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'echarger',
            },
        ),
        migrations.CreateModel(
            name='TeslaCharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(default='', max_length=64, unique=True)),
                ('location_type', models.CharField(max_length=64)),
                ('open_soon', models.SmallIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=32)),
                ('street_address', models.CharField(max_length=64)),
                ('extended_address', models.CharField(default='', max_length=64)),
                ('locality', models.CharField(max_length=16)),
                ('tel_info', models.CharField(max_length=64)),
                ('opening_time_info', models.CharField(max_length=64)),
                ('charger_info', models.CharField(max_length=64)),
                ('charge_info', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'teslacharger',
            },
        ),
    ]
