# Generated by Django 2.0.7 on 2018-07-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='echarger',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teslacharger',
            table=None,
        ),
    ]
