# Generated by Django 2.0.7 on 2018-07-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0002_auto_20180720_1044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='echarger',
            table='echarger',
        ),
        migrations.AlterModelTable(
            name='teslacharger',
            table='teslacharger',
        ),
    ]
