# Generated by Django 2.0.7 on 2018-07-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charger', '0004_auto_20180720_1055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='echarger',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teslacharger',
            table=None,
        ),
    ]
