# Generated by Django 2.0.7 on 2018-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('session_key', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=512)),
                ('token_time', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'useraccess',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('car_type', models.CharField(max_length=1024)),
                ('road_book', models.CharField(max_length=1024)),
                ('charger', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
