# Generated by Django 2.0.7 on 2018-07-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_time', models.TimeField(auto_created=True)),
                ('username', models.CharField(max_length=150)),
                ('session_key', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('car_type', models.CharField(max_length=1024)),
                ('road_book', models.CharField(max_length=1024)),
                ('charge', models.CharField(max_length=1024)),
            ],
        ),
    ]
