# Generated by Django 2.0.7 on 2018-07-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccess',
            table='zhuangyou.useraccess',
        ),
    ]
