# Generated by Django 2.0.7 on 2018-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='token_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
