# Generated by Django 2.0.7 on 2018-07-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxUser', '0003_auto_20180720_1044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccess',
            table='useraccess',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
