# Generated by Django 2.0.7 on 2018-07-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxUser', '0004_auto_20180720_1048'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccess',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
