# Generated by Django 2.0.7 on 2018-07-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128, unique=True)),
                ('areaName', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=128)),
                ('connectorType', models.SmallIntegerField()),
                ('currentType', models.SmallIntegerField()),
                ('freeNum', models.SmallIntegerField()),
                ('chargeId', models.CharField(default='', max_length=64, unique=True)),
                ('images', models.CharField(max_length=128, null=True)),
                ('isGs', models.SmallIntegerField()),
                ('lat', models.FloatField()),
                ('link', models.SmallIntegerField()),
                ('lng', models.FloatField()),
                ('mapIcon', models.CharField(max_length=128)),
                ('maxOutPower', models.SmallIntegerField()),
                ('operatorTypes', models.CharField(max_length=32)),
                ('payType', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('plugType', models.SmallIntegerField()),
                ('priceRational', models.IntegerField()),
                ('province', models.CharField(max_length=32)),
                ('quantity', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('serviceCode', models.SmallIntegerField()),
                ('standard', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('supportOrder', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeslaCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
